services:
  web:
    build: .
    ports:
      - "8080:3000"
    environment:
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_MASTER_KEY=7119dc9bb9c6167e706fa2b9ee058084
    volumes:
      - ./log:/rails/log
      - ./tmp:/rails/tmp
      - ./main_pages:/rails/main_pages
      - ./side_panels:/rails/side_panels
      - ./security:/rails/security
    restart: unless-stopped
